### ISSUE TITLE
Create Subtask Example

### ISSUE THREAD

**Issue by kaela** [kaela/sassyhtml#1]
- [x] write the blog post
- [x] make this ticket
- [ ] grab a screenshot
- [ ] post the blog post
